// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTT5T572ovOdKhiGD_DfLGtyFg3uAg4zY',
    appId: '1:311120020396:web:e001cb810a870bed733009',
    messagingSenderId: '311120020396',
    projectId: 'eatly-0',
    authDomain: 'eatly-0.firebaseapp.com',
    storageBucket: 'eatly-0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXqk26pJJtFrrP88DUDeKr6Oum8Qv7R_4',
    appId: '1:311120020396:android:5ea3fbcd9ab2160b733009',
    messagingSenderId: '311120020396',
    projectId: 'eatly-0',
    storageBucket: 'eatly-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQAKuwRN8vzgz-h6Vo5ohzQNKW3m3rIa8',
    appId: '1:311120020396:ios:67f5a8116a7f7997733009',
    messagingSenderId: '311120020396',
    projectId: 'eatly-0',
    storageBucket: 'eatly-0.firebasestorage.app',
    iosBundleId: 'com.example.eatly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQAKuwRN8vzgz-h6Vo5ohzQNKW3m3rIa8',
    appId: '1:311120020396:ios:67f5a8116a7f7997733009',
    messagingSenderId: '311120020396',
    projectId: 'eatly-0',
    storageBucket: 'eatly-0.firebasestorage.app',
    iosBundleId: 'com.example.eatly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTT5T572ovOdKhiGD_DfLGtyFg3uAg4zY',
    appId: '1:311120020396:web:e4101c89bd853f8c733009',
    messagingSenderId: '311120020396',
    projectId: 'eatly-0',
    authDomain: 'eatly-0.firebaseapp.com',
    storageBucket: 'eatly-0.firebasestorage.app',
  );
}
